# Header
menu:
  Home: /
  About: /about
  Archives: /archives
rss: /rss2.xml

# Content
excerpt_link: Read More
fancybox: true

# Sidebar
sidebar: right

# Search form
search: true

# Widgets
widgets:
- about
- category
- tag
- tagcloud
- archive
- recent_posts
- sidebar_ads

# Miscellaneous
adsense:
  account_id: 
  autoads: false
  header:
  sidebar: 
  post_header:
  post_footer:
  top_mid_article:
google_analytics:
favicon: /favicon.png
twitter:
google_plus:
fb_admins:
fb_app_id:

fb_pages:

aboutme:
about:
  author: true
  twitter: true
  aboutme: true
  description: true

common_keywords:
